// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZUlRlEDO-pyQtK0NZLI6Olal6YnS4GaA',
    appId: '1:555662726251:web:692319ebe2d1db534e0d2e',
    messagingSenderId: '555662726251',
    projectId: 'megha-tuition',
    authDomain: 'megha-tuition.firebaseapp.com',
    storageBucket: 'megha-tuition.firebasestorage.app',
    measurementId: 'G-08NGZVJVHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2oUcM-UWwS-XVGdG697QJed17nXdWlcs',
    appId: '1:555662726251:android:47b01e7dfa56c26b4e0d2e',
    messagingSenderId: '555662726251',
    projectId: 'megha-tuition',
    storageBucket: 'megha-tuition.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV2-bk2C6o_TItJDAcH1S36hY4oOAcgN8',
    appId: '1:555662726251:ios:a2c124c5c31ee0774e0d2e',
    messagingSenderId: '555662726251',
    projectId: 'megha-tuition',
    storageBucket: 'megha-tuition.firebasestorage.app',
    iosBundleId: 'com.example.meghatuition.meghaTuition',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV2-bk2C6o_TItJDAcH1S36hY4oOAcgN8',
    appId: '1:555662726251:ios:a2c124c5c31ee0774e0d2e',
    messagingSenderId: '555662726251',
    projectId: 'megha-tuition',
    storageBucket: 'megha-tuition.firebasestorage.app',
    iosBundleId: 'com.example.meghatuition.meghaTuition',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZUlRlEDO-pyQtK0NZLI6Olal6YnS4GaA',
    appId: '1:555662726251:web:02181cf7d032d2634e0d2e',
    messagingSenderId: '555662726251',
    projectId: 'megha-tuition',
    authDomain: 'megha-tuition.firebaseapp.com',
    storageBucket: 'megha-tuition.firebasestorage.app',
    measurementId: 'G-8J5QGW73T7',
  );
}
